### ISSUE TITLE
Estadísticas equipo

### ISSUE THREAD

**Issue by claudiaRecioAlcaide** [baldo3/CapyTournament#2]
Basándonos en el diagrama subido decidiri qué estadísticas de equipo estrán disponibles.

**Comment by javijones00** [comment]
ESTADISTICAS:

- Lista de torneos
- Torneos ganados 
- Porcentaje de victoria de torneos
- Victorias
- Derrotas
- Winrate
- KDA del equipo
- MVP del equipo
